spring.application.name=backend
server.port=8080

# Conexión a la Base de Datos en AWS RDS (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:pedidosdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Configuración de identidad con Entra ID (Exigiendo tokens v2.0)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_API_CLIENT_ID}