spring.application.name=backend

# Configuración de la base de datos Cloud (Oracle SQL)
spring.datasource.url=jdbc:oracle:thin:@//tu-endpoint-cloud:1521/tu_servicio
spring.datasource.username=tu_usuario
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Configuración de identidad con Entra ID (OAuth2 Resource Server)
# Reemplaza el TENANT_ID con el de tu directorio en Azure
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/TU_TENANT_ID/